/* This file has been autogenerated.
DO NOT manually edit it.
Run `python manage.py transpile_models` to update it. */

export type User = {
  id: number,
  is_superuser: boolean,
  username: string,
  email: string,
  is_active: boolean,
  date_joined: string,
}

export type Language = {
  id: number,
  name: string,
}
