# Generated by Django 3.2 on 2024-03-20 03:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_form', models.CharField(max_length=32)),
                ('translation', models.CharField(max_length=128)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.language')),
            ],
        ),
        migrations.CreateModel(
            name='LemmaAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField()),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.lemma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('text', models.CharField(max_length=256)),
                ('translation', models.CharField(max_length=256)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.document')),
            ],
        ),
        migrations.CreateModel(
            name='WordInSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.lemma')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField()),
                ('trial_type', models.CharField(choices=[('cz', 'cloze'), ('ct', 'choose translation'), ('cc', 'choose citation form')], max_length=2)),
                ('choices', models.CharField(max_length=256)),
                ('correct', models.BooleanField()),
                ('easiness', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('lemma_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.lemmaadd')),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Substring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.wordinsentence')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.language'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(fields=('document', 'position'), name='unique_sentence_position'),
        ),
    ]
