# Generated by Django 5.0.3 on 2024-03-25 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0002_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordinsentence',
            name='lemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.lemma'),
        ),
    ]
