# Generated by Django 5.0.3 on 2024-03-27 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0004_alter_substring_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='current_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spaced_repetition.language'),
        ),
    ]
