# Generated by Django 5.0.3 on 2024-03-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0005_alter_usersettings_current_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.language')),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.lemma')),
            ],
        ),
    ]
