# Generated by Django 5.0.3 on 2024-03-29 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0007_sentenceadd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lemmaadd',
            constraint=models.UniqueConstraint(fields=('user', 'lemma'), name='unique_user_and_lemma'),
        ),
        migrations.AddConstraint(
            model_name='sentenceadd',
            constraint=models.UniqueConstraint(fields=('user', 'sentence'), name='unique_user_and_sentence'),
        ),
    ]
