# Generated by Django 5.0.3 on 2024-03-31 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0008_lemmaadd_unique_user_and_lemma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='choice',
            field=models.CharField(default='groot', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentenceadd',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adds', to='spaced_repetition.sentence'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.sentence'),
        ),
    ]
