# Generated by Django 5.0.3 on 2024-04-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0009_trial_choice_alter_sentenceadd_sentence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='language',
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.language')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.collection'),
            preserve_default=False,
        ),
    ]
