# Generated by Django 5.0.3 on 2024-04-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0010_remove_document_language_document_order_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='image',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
