# Generated by Django 5.0.3 on 2024-04-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0013_lemma_metadata_metadatatrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='format_level',
            field=models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('p', 'p'), ('ns', 'ns')], default='p', max_length=2),
        ),
    ]
