# Generated by Django 5.0.3 on 2024-04-17 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0014_sentence_format_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='format_level',
            field=models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('p', 'p'), ('ns', 'new section')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='trial',
            name='lemma_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.lemmaadd'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.sentence'),
        ),
    ]
