# Generated by Django 5.0.3 on 2024-05-01 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0015_alter_sentence_format_level_alter_trial_lemma_add_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.collection'),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.language'),
        ),
        migrations.AlterField(
            model_name='lemmaadd',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.lemma'),
        ),
        migrations.AlterField(
            model_name='lemmaadd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadatatrial',
            name='lemma_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.lemmaadd'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.document'),
        ),
        migrations.AlterField(
            model_name='sentenceadd',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adds', to='spaced_repetition.sentence'),
        ),
        migrations.AlterField(
            model_name='sentenceadd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.language'),
        ),
        migrations.AlterField(
            model_name='word',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.lemma'),
        ),
        migrations.AlterField(
            model_name='wordinsentence',
            name='lemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.lemma'),
        ),
        migrations.AlterField(
            model_name='wordinsentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spaced_repetition.sentence'),
        ),
    ]
