# Generated by Django 5.0.3 on 2024-05-01 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0016_alter_document_collection_alter_lemma_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.lemma'),
        ),
    ]
