# Generated by Django 5.0.3 on 2024-05-09 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0017_alter_word_lemma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordinsentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='words_in_sentence', to='spaced_repetition.sentence'),
        ),
    ]
