# Generated by Django 5.0.3 on 2024-06-20 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0018_alter_wordinsentence_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='lemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spaced_repetition.lemma'),
        ),
    ]
