# Generated by Django 5.0.3 on 2024-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0019_alter_word_lemma'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'lemma'), name='unique_word_and_lemma'),
        ),
    ]
