# Generated by Django 5.0.7 on 2024-08-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0020_word_unique_word_and_lemma'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='occurrences',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
